In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('/Users/foreignting/Downloads/online_shoppers_intention.csv')

In [3]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [4]:
df.shape

(12330, 18)

In [5]:
df.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [6]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [7]:
df.Month.unique()

array(['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep',
       'Dec'], dtype=object)

In [8]:
df.VisitorType.unique()

array(['Returning_Visitor', 'New_Visitor', 'Other'], dtype=object)

In [9]:
# словари для категориальных признаков
d2n = {'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4, 'May':5, 'June':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12}
n2d = dict((v,k) for k,v in d2n.items())

vt2n = {'Returning_Visitor':1, 'New_Visitor':2, 'Other':3}
n2vt = dict((v,k) for k,v in vt2n.items())

In [10]:
df.Month = df.Month.map(d2n)
df.VisitorType = df.VisitorType.map(vt2n)
df.Weekend = df.Weekend * 1
df.Revenue = df.Revenue * 1

In [11]:
# сравнение значений признаков покупающих / непокупающих пользователей 
df[df['Revenue']>0].describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
count,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.0
mean,3.393606,119.483244,0.786164,57.611427,48.210168,1876.209615,0.005117,0.019555,27.264518,0.023166,8.661950,2.092767,2.453354,3.082285,4.021488,1.237945,0.261530,1.0
std,3.730527,201.114732,1.521176,171.619131,58.267365,2312.214392,0.012185,0.016463,35.191954,0.123521,3.104622,0.929779,1.897042,2.407173,3.987140,0.445200,0.439583,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0
25%,0.000000,0.000000,0.000000,0.000000,15.000000,541.906250,0.000000,0.009521,3.641144,0.000000,5.000000,2.000000,2.000000,1.000000,2.000000,1.000000,0.000000,1.0
50%,2.000000,52.366667,0.000000,0.000000,29.000000,1109.906250,0.000000,0.016000,16.758134,0.000000,11.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.000000,1.0
75%,5.000000,151.083333,1.000000,19.000000,57.000000,2266.011310,0.006452,0.025000,38.897742,0.000000,11.000000,2.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.0
max,26.000000,2086.750000,12.000000,1767.666667,534.000000,27009.859430,0.200000,0.200000,361.763742,1.000000,12.000000,8.000000,13.000000,9.000000,20.000000,3.000000,1.000000,1.0

In [12]:
df[df['Revenue']==0].describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
count,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.0
mean,2.117732,73.740111,0.451833,30.236237,28.714642,1069.987809,0.025317,0.047378,1.975998,0.068432,7.467089,2.129726,2.339474,3.159278,4.078392,1.135291,0.227308,0.0
std,3.202481,171.017970,1.211582,133.909306,40.744717,1803.797757,0.051877,0.051231,9.072424,0.209054,3.410897,0.907835,1.681790,2.400493,4.032220,0.360889,0.419113,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.0
25%,0.000000,0.000000,0.000000,0.000000,6.000000,151.000000,0.000000,0.015560,0.000000,0.000000,5.000000,2.000000,2.000000,1.000000,2.000000,1.000000,0.000000,0.0
50%,0.000000,0.000000,0.000000,0.000000,16.000000,510.190000,0.004255,0.028571,0.000000,0.000000,7.000000,2.000000,2.000000,3.000000,2.000000,1.000000,0.000000,0.0
75%,3.000000,83.000000,0.000000,0.000000,35.000000,1331.816667,0.020000,0.053846,0.000000,0.000000,11.000000,3.000000,2.000000,4.000000,4.000000,1.000000,0.000000,0.0
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,246.758590,1.000000,12.000000,8.000000,13.000000,9.000000,20.000000,3.000000,1.000000,0.0

Покупатели:
* проводят больше времени на сайте;
* имеют меньшие значения BounceRate и ExitRates;
* имеют бОльшие значения PageValue
______

* SpecialDay линейно не влияет на покупки (может быть в промо дни больше "случайных" посетителей, записей SpecialDay = 1 -- мало)
* классы несбалансированы

In [13]:
# колонка общего времени на сайте
df['Duration'] = df['Administrative_Duration'] + df['Informational_Duration'] + df['ProductRelated_Duration']

In [14]:
# сплит данных
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['Revenue']), df['Revenue'], test_size=0.2)

In [15]:
# оверсемплинг для баланса
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=0)
x_ros,y_ros = ros.fit_resample(df.drop(columns=['Revenue']), df['Revenue'])

In [16]:
# сплит новых данных
from sklearn.model_selection import train_test_split

ros_X_train, ros_X_test, ros_y_train, ros_y_test = train_test_split(
    x_ros, y_ros, test_size=0.2)

In [25]:
# классификатор
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(n_estimators=400, random_state=0)
clf.fit(ros_X_train, ros_y_train)

# проверка на оригинальном наборе
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
print(accuracy_score(y_test,clf.predict(X_test)))
print(recall_score(y_test,clf.predict(X_test)))
print(precision_score(y_test,clf.predict(X_test)))
print(f1_score(y_test,clf.predict(X_test)))

0.8714517437145174
0.8123249299719888
0.5370370370370371
0.6465997770345597

In [26]:
# результаты без оверсемплинга
clf.fit(X_train, y_train)
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
print(accuracy_score(y_test,clf.predict(X_test)))
print(recall_score(y_test,clf.predict(X_test)))
print(precision_score(y_test,clf.predict(X_test)))
print(f1_score(y_test,clf.predict(X_test)))

0.8982157339821574
0.5770308123249299
0.673202614379085
0.6214177978883861

* подняли f1
* попробовать другой семплинг/и/или добавить веса классам

In [27]:
# пайплайн

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

duration_sum = lambda x: x['Administrative Duration'] + x['Informational Duration'] + x['Product Related Duration']

transformer = ColumnTransformer(
    transformers=[
        ('month', FunctionTransformer(lambda x: x.map(d2n)), ['Month']),
        ('visitor_type', FunctionTransformer(lambda x: x.map(vt2n)), ['VisitorType']),
        ('weekend', FunctionTransformer(lambda x: x * 1), ['Weekend']),
        ('revenue', FunctionTransformer(lambda x: x * 1), ['Revenue']),
        ('total_duration', FunctionTransformer(duration_sum), ['Administrative Duration', 'Informational Duration', 'Product Related Duration'])
    ],
    remainder='passthrough'
)

pipeline = Pipeline(steps=[
    ('transformer', transformer),
    ('classifier', clf)
])